### ISSUE TITLE
RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by arosell-hsco** [download-directory/download-directory.github.io#72]
After outputting in the console "Zipping X files…"

If trows this exceptions and does not download anything: 

```js
UZIP.js:187 Uncaught (in promise) RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at f._writeHeader (UZIP.js:187:12)
    at f.encode (UZIP.js:136:12)
    at index.js:192:26
```

**Comment by GoombaProgrammer** [comment]
Same problem here
